### ISSUE TITLE
fontbakery QA check

### ISSUE THREAD

**Issue by laerm0** [geeztypes/inku#2]
Hey @yosiasz –

I have run the font through [fontbakery](https://github.com/googlefonts/fontbakery), the Google Fonts QA check tool. The command to run this check is `fontbakery check-googlefonts fonts/ttf/Inku-Regular.ttf --loglevel INFO --ghmarkdown check.md`. Some of the errors can be ignored in your case (anything that compares it to a file on Google Fonts, obviously). A few of these would require fixes but they are all terribly simple.

Let me know if you need any further tips. 👍🏻

[check.txt](https://github.com/geeztypes/inku/files/4339176/check.txt) is in markdown, which github somehow doesn't support as a filetype allowed as a attachment…? Strange.

**Comment by yosiasz** [comment]
@laerm0 fontbakery QA checks ran. Posted fixes. what a bear of a process! yuk

**Comment by yosiasz** [comment]
By the way @laerm0 this font will cover 2 or more languages: Amharic, Tigrinya. I will get the others at another time.

**Comment by yosiasz** [comment]
👌
