### ISSUE TITLE
Vendor ID

### ISSUE THREAD

**Issue by laerm0** [geeztypes/inku#6]
Hi –

The vendor ID is too long. It is actually an abbreviation no longer than 4 characters. It needs to be [registered with Microsoft](https://docs.microsoft.com/en-us/typography/vendors/register). It's really a very simple process and only takes them a day or two to respond usually.

**Comment by yosiasz** [comment]
Ok, registered will wait and see.

**Comment by yosiasz** [comment]
Registered!

GFT | Geez Font Types

**Comment by laerm0** [comment]
Quick response! Cool. 😁
